<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>WinNewsWire.FeedFinder</RootNamespace>
    <AssemblyName>WinNewsWire.FeedFinder</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Parsers\Parsers.csproj" />
    <ProjectReference Include="..\Web\Web.csproj" />
  </ItemGroup>
</Project>
