namespace WinNewsWire.AppShared.Exporters;

/// <summary>Port of <c>OPMLExporter</c>.</summary>
public static class OpmlExporter
{
    public static string OPMLString(Account.Account account, string title)
    {
        var esc = System.Security.SecurityElement.Escape(title) ?? "";
        var head = $"""
            <?xml version="1.0" encoding="UTF-8"?>
            <!-- OPML generated by WinNewsWire -->
            <opml version="1.1">
                <head>
                    <title>{esc}</title>
                </head>
            <body>

            """;
        var body = account.ExportOpml();
        // Extract inner <body> content from Account.ExportOpml output.
        int start = body.IndexOf("<body>");
        int end = body.IndexOf("</body>");
        if (start >= 0 && end > start)
            body = body.Substring(start + "<body>".Length, end - start - "<body>".Length);
        return head + body + "    </body>\n</opml>\n";
    }

    public static Task ExportAsync(Account.Account account, string path)
        => File.WriteAllTextAsync(path, OPMLString(account, account.Name));
}
