<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>WinNewsWire.Feedbin</RootNamespace>
    <AssemblyName>WinNewsWire.Feedbin</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Web\Web.csproj" />
    <ProjectReference Include="..\Articles\Articles.csproj" />
    <ProjectReference Include="..\ArticlesDatabase\ArticlesDatabase.csproj" />
    <ProjectReference Include="..\SyncDatabase\SyncDatabase.csproj" />
    <ProjectReference Include="..\Account\Account.csproj" />
    <ProjectReference Include="..\Secrets\Secrets.csproj" />
  </ItemGroup>
</Project>
